/*
====================================================================================
DDL SCRIPT: CREATE BRONZE LAYER
====================================================================================
Script Purpose:
    This script creates tables in the 'bronze' schema, dropping exisiting tables.
    if they already exists.
    Run this script to re-define the DDL structure of bronze tables.
=====================================================================================    
*/



Drop table if exists bronze.crm_cust_info;
  CREATE TABLE bronze.crm_cust_info (
  cst_id               INT,
  cst_key              NVARCHAR(50),
  cst_firstname        NVARCHAR(50),
  cst_lastname         NVARCHAR(50),
  cst_material_status  NVARCHAR(50),
  cst_gndr             NVARCHAR(50),
  cst_create_date      TIMESTAMP
  );

Drop table if exists bronze.crm_prd_info;
 CREATE TABLE bronze.crm_prd_info (
  prd_id INT,
  prd_key      NVARCHAR(50),
  prd_nm       NVARCHAR(50),
  prd_cost     INT,
  prd_line     NVARCHAR(50),
  prd_start_dt TIMESTAMP,
  prd_end_dt   TIMESTAMP
  );

Drop table if exists bronze.crm_sales_details;
 CREATE TABLE bronze.crm_sales_details(
  sls_ord_num  NVARCHAR(50),
  sls_prd_key  NVARCHAR(50),
  sls_cust_id  INT,
  sls_order_dt INT,
  sls_ship_dt  INT,
  sls_due_dt   INT,
  sls_sales    INT,
  sls_quantity INT,
  sls_price    INT
  );

Drop table if exists bronze.erp_loc_a101;
  create table bronze.erp_loc_a101 (
  cid   NVARCHAR(50),
  cntry NVARCHAR(50) 
  );

Drop table if exists bronze.erp_cust_az12;
  create table bronze.erp_cust_az12 (
  cid    NVARCHAR(50),
  bdate  TIMESTAMP,
  gen    NVARCHAR(50)
  );

Drop table if exists bronze.erp_px_cat_g1v2;
  create table bronze.erp_px_cat_g1v2 (
  id          NVARCHAR(50),
  cat         NVARCHAR(50),
  subcat      NVARCHAR(50),
  maintenance NVARCHAR(50)
);
  
  
